name: Webpack Build

on:
  push:
    branches:
      - main

jobs:
  webpack-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Build Production Bundle
      run: |
        npm ci
        NODE_ENV=production webpack --mode production

    - name: Add and Commit
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: './docs/public/dist -f'
        remove: '-rf . :!docs'
        message: 'Update production bundle'
        push: origin HEAD:client -f
        pathspec_error_handling: exitImmediately
