name: Webpack Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Build
      run: |
        npm ci
        NODE_ENV=production webpack --mode production

    - name: Add and Commit
      uses: EndBug/add-and-commit@v9
      with:
        remove: '-r .'
        add: './docs/public/dist --force'
        default_author: github_actions
        message: 'Update production bundle'
        push: origin HEAD:client --force
        pathspec_error_handling: exitImmediately
